from typing import Dict

try:
    from .base_provider import BaseAIProvider
except ImportError:
    from base_provider import BaseAIProvider
import json
import logging

logger = logging.getLogger(__name__)

try:
    import anthropic
    CLAUDE_AVAILABLE = True
except ImportError:
    CLAUDE_AVAILABLE = False
    logger.warning("Anthropic library not available. Install with: pip install anthropic")

class ClaudeProvider(BaseAIProvider):
    """Anthropic Claude provider"""
    
    def __init__(self, api_key: str, model_name: str = "claude-3-5-sonnet-20241022", base_url: str = None):
        if not CLAUDE_AVAILABLE:
            raise ImportError("Anthropic library is not installed")
        super().__init__(api_key, model_name, base_url)
        self.client = anthropic.Anthropic(api_key=api_key)
    
    async def generate_strategy(self, prompt: str) -> Dict[str, str]:
        """Generate strategy using Claude"""
        try:
            system_instruction = self.get_system_instruction()
            
            message = self.client.messages.create(
                model=self.model_name,
                max_tokens=4000,
                system=system_instruction,
                messages=[
                    {
                        "role": "user",
                        "content": f"{prompt}\n\nPlease respond with a JSON object containing 'code' and 'explanation' fields."
                    }
                ]
            )
            
            result_text = message.content[0].text if message.content else ""
            if not result_text:
                raise ValueError("No content generated")
            
            # Try to parse JSON from response
            try:
                # Extract JSON from markdown code blocks if present
                if "```json" in result_text:
                    json_start = result_text.find("```json") + 7
                    json_end = result_text.find("```", json_start)
                    result_text = result_text[json_start:json_end].strip()
                elif "```" in result_text:
                    json_start = result_text.find("```") + 3
                    json_end = result_text.find("```", json_start)
                    result_text = result_text[json_start:json_end].strip()
                
                result = json.loads(result_text)
            except json.JSONDecodeError:
                # If JSON parsing fails, try to extract code from response
                if "def strategy_logic" in result_text:
                    code_start = result_text.find("def strategy_logic")
                    code_end = result_text.find("\n\n", code_start)
                    if code_end == -1:
                        code_end = len(result_text)
                    code = result_text[code_start:code_end]
                    explanation = "Strategy generated by Claude"
                else:
                    raise ValueError("Could not parse response")
                result = {"code": code, "explanation": explanation}
            
            return {
                "code": result.get("code", ""),
                "explanation": result.get("explanation", "")
            }
            
        except Exception as e:
            logger.error(f"Claude strategy generation failed: {str(e)}")
            # Fallback to default strategy
            return {
                "code": """import pandas as pd
import numpy as np

def strategy_logic(df: pd.DataFrame) -> pd.Series:
    # Default SMA Crossover strategy
    df['SMA_20'] = df['Close'].rolling(window=20).mean()
    df['SMA_50'] = df['Close'].rolling(window=50).mean()
    
    signals = pd.Series(0, index=df.index)
    signals[df['SMA_20'] > df['SMA_50']] = 1
    signals[df['SMA_20'] < df['SMA_50']] = -1
    
    return signals""",
                "explanation": f"Error connecting to Claude. Returned default SMA Crossover strategy. Error: {str(e)}"
            }
    
    async def test_connection(self) -> bool:
        """Test Claude connection"""
        try:
            message = self.client.messages.create(
                model=self.model_name,
                max_tokens=10,
                messages=[{"role": "user", "content": "Test"}]
            )
            return message.content[0].text is not None if message.content else False
        except Exception as e:
            logger.error(f"Claude connection test failed: {str(e)}")
            return False
